<definitions name="SampleService" targetNamespace="http://localhost:5001/wsdl/SampleService.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://localhost:5001/wsdl/SampleService.wsdl"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 
    <message name="SampleRequest">
        <part name="firstName" type="xsd:string"/>
    </message>
    <message name="SampleResponse">
        <part name="greeting" type="xsd:string"/>
    </message>
    <portType name="Sample_PortType">
        <operation name="sampleOperation">
            <input message="tns:SampleRequest"/>
            <output message="tns:SampleResponse"/>
        </operation>
    </portType>
    <binding name="SampleService" type="tns:Sample_PortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="sampleOperation">
            <soap:operation soapAction="sampleOperation"/>
            <input>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                    namespace="urn:sample:sample-service" use="encoded"/>
            </input>
            <output>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                    namespace="urn:sample:sample-service" use="encoded"/>
            </output>
        </operation>
    </binding>
    <service name="Sample_Service">
        <documentation>WSDL File for SampleService</documentation>
        <port binding="tns:SampleService" name="Sample_Port">
            <soap:address location="http://localhost:5001/sample-service"/>
        </port>
    </service>
</definitions>